name: bluegreendeployment
version: "0.1"
services:
  blue:
    image: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}
    restart: on-failure
    depends_on:
      - loadbalancer
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:5000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 25s
    environment:
      VIRTUAL_HOST: test22
      VIRTUAL_PORT: 5000


  green:
    image: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}
    restart: on-failure
    depends_on:
      - loadbalancer
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:5000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 25s
    environment:
      VIRTUAL_HOST: test22
      VIRTUAL_PORT: 5000

  loadbalancer:
    image: nginxproxy/nginx-proxy:latest
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: test22
